### ISSUE TITLE
Error in BOOKED page

### ISSUE THREAD

**Issue by psantosh16** [psantosh16/Advance-Parking-Management-System#45]
Problem :-  
**EXCEPTION CAUGHT BY WIDGETS LIBRARY** 

The following NoSuchMethodError was thrown building StreamBuilder<QuerySnapshot<Object?>>(dirty,
dependencies: [MediaQuery], state: _StreamBuilderBaseState<QuerySnapshot<Object?>,
AsyncSnapshot<QuerySnapshot<Object?>>>#8c903):
Class 'String' has no instance method '<'.
Receiver: "2-11-2023  08:15"
Tried calling: <(2023110123)

The relevant error-causing widget was:
  StreamBuilder<QuerySnapshot<Object?>>

@OmkarDate29 @Niranjan-Dorage

**Comment by psantosh16** [comment]
![Screenshot 2023-11-02 at 12 00 44 AM](https://github.com/psantosh16/Advance-Parking-Management-System/assets/99491679/0d2f5088-6952-4155-9e7a-c4bf872aa117)

**Comment by Niranjan-Dorage** [comment]
check it now @psantosh16

**Comment by Niranjan-Dorage** [comment]
in database there was a old ticket with different datatype now i have removed it .

**Comment by Niranjan-Dorage** [comment]
you can remove this issue @psantosh16

**Comment by psantosh16** [comment]
Ok

**Comment by psantosh16** [comment]
I'll close it by checking 🙂

**Comment by Niranjan-Dorage** [comment]
![image](https://github.com/psantosh16/Advance-Parking-Management-System/assets/108044574/af892e7b-4f93-4e88-93a5-fa5e34ba67b0)
why only this transaction dont have "datetime" field ?
all others have that field ...........
check by adding new tickets please
@psantosh16
